[world]
kind = "WorldContract"
class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
original_class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
abi = "manifests/sepolia/abis/deployments/dojo_world_world.json"
address = "0x4404b47fc2a4251f05e5013fc77250c0d8de65c03b7d48893016ee751327e9e"
transaction_hash = "0x7caf71558f73e9936ade94992936fb466c6045f5e2fc97161d99e4573b91bd9"
seed = "mancala"
name = "dojo::world::world"

[world.metadata]
profile_name = "sepolia"
rpc_url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_6"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
class_hash = "0x73105e8f5b180b9a6d10ff4a1c02e974a237d65e3512cff2f0a3db026c81753"
original_class_hash = "0x73105e8f5b180b9a6d10ff4a1c02e974a237d65e3512cff2f0a3db026c81753"
base_class_hash = "0x0"
abi = "manifests/sepolia/abis/deployments/contracts/mancala_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "mancala::systems::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x1873cbec55a7cdcf06d927862bafc5fbab77be732968e46dd32dfff29814014"
original_class_hash = "0x1873cbec55a7cdcf06d927862bafc5fbab77be732968e46dd32dfff29814014"
abi = "manifests/sepolia/abis/deployments/models/mancala_models_mancala_game_game_id.json"
name = "mancala::models::mancala_game::game_id"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "game_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xdb89747801cdcd3bc7df959974c149596121fafcdd3cb8a388d7841f510cb8"
original_class_hash = "0xdb89747801cdcd3bc7df959974c149596121fafcdd3cb8a388d7841f510cb8"
abi = "manifests/sepolia/abis/deployments/models/mancala_models_mancala_game_mancala_game.json"
name = "mancala::models::mancala_game::mancala_game"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "player_one"
type = "ContractAddress"
key = false

[[models.members]]
name = "player_two"
type = "ContractAddress"
key = false

[[models.members]]
name = "current_player"
type = "ContractAddress"
key = false

[[models.members]]
name = "last_move"
type = "u64"
key = false

[[models.members]]
name = "time_between_move"
type = "u64"
key = false

[[models.members]]
name = "winner"
type = "ContractAddress"
key = false

[[models.members]]
name = "status"
type = "GameStatus"
key = false

[[models.members]]
name = "is_private"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7e1830563f39a43e5e88fef3c6b005aca7c8694d522f2a093e183556021f2f8"
original_class_hash = "0x7e1830563f39a43e5e88fef3c6b005aca7c8694d522f2a093e183556021f2f8"
abi = "manifests/sepolia/abis/deployments/models/mancala_models_player_game_player.json"
name = "mancala::models::player::game_player"

[[models.members]]
name = "address"
type = "ContractAddress"
key = true

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "pit1"
type = "u8"
key = false

[[models.members]]
name = "pit2"
type = "u8"
key = false

[[models.members]]
name = "pit3"
type = "u8"
key = false

[[models.members]]
name = "pit4"
type = "u8"
key = false

[[models.members]]
name = "pit5"
type = "u8"
key = false

[[models.members]]
name = "pit6"
type = "u8"
key = false

[[models.members]]
name = "mancala"
type = "u8"
key = false

[[models.members]]
name = "restart_requested"
type = "bool"
key = false
