kind = "DojoModel"
class_hash = "0x2af0729b10b86352efca71c1632101b5629a923d27f96049e8e1f1121f304a5"
original_class_hash = "0x2af0729b10b86352efca71c1632101b5629a923d27f96049e8e1f1121f304a5"
abi = "manifests/dev/abis/base/models/mancala_models_mancala_game_mancala_game.json"
name = "mancala::models::mancala_game::mancala_game"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "player_one"
type = "ContractAddress"
key = false

[[members]]
name = "player_two"
type = "ContractAddress"
key = false

[[members]]
name = "current_player"
type = "ContractAddress"
key = false

[[members]]
name = "winner"
type = "ContractAddress"
key = false

[[members]]
name = "status"
type = "GameStatus"
key = false

[[members]]
name = "is_private"
type = "bool"
key = false
