kind = "DojoModel"
class_hash = "0x7e1830563f39a43e5e88fef3c6b005aca7c8694d522f2a093e183556021f2f8"
original_class_hash = "0x7e1830563f39a43e5e88fef3c6b005aca7c8694d522f2a093e183556021f2f8"
abi = "manifests/dev/abis/base/models/mancala_models_player_game_player.json"
name = "mancala::models::player::game_player"

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "pit1"
type = "u8"
key = false

[[members]]
name = "pit2"
type = "u8"
key = false

[[members]]
name = "pit3"
type = "u8"
key = false

[[members]]
name = "pit4"
type = "u8"
key = false

[[members]]
name = "pit5"
type = "u8"
key = false

[[members]]
name = "pit6"
type = "u8"
key = false

[[members]]
name = "mancala"
type = "u8"
key = false

[[members]]
name = "restart_requested"
type = "bool"
key = false
