kind = "DojoModel"
class_hash = "0x76f6d0cb196ab99665601e7d2132cecf5a83d11c5d8d7c96469d70aa0d3ad08"
original_class_hash = "0x76f6d0cb196ab99665601e7d2132cecf5a83d11c5d8d7c96469d70aa0d3ad08"
abi = "manifests/dev/abis/base/models/mancala_models_mancala_game_mancala_game.json"
name = "mancala::models::mancala_game::mancala_game"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "player_one"
type = "ContractAddress"
key = false

[[members]]
name = "player_two"
type = "ContractAddress"
key = false

[[members]]
name = "current_player"
type = "ContractAddress"
key = false

[[members]]
name = "last_move"
type = "u64"
key = false

[[members]]
name = "time_between_move"
type = "u64"
key = false

[[members]]
name = "winner"
type = "ContractAddress"
key = false

[[members]]
name = "status"
type = "GameStatus"
key = false

[[members]]
name = "is_private"
type = "bool"
key = false
