[world]
name = "Mancala"
description = "Mancala is a fully on-chain PvP strategy boardgame built on Dojo."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/realm-of-ra/mancala"
seed = "mancala-denstwo"

[world.socials]
x = "https://x.com/realm_of_ra"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/realm-of-ra/mancala"
telegram = "https://t.me/dojoengine"

[namespace]
default = "mancala_denstwo"

[writers]
"mancala_denstwo" = ["mancala_denstwo-Mancala", "mancala_denstwo-PlayerProfile"]
"mancala_denstwo-TrophyCreation" = ["mancala_denstwo-Mancala"]
"mancala_denstwo-TrophyProgression" = ["mancala_denstwo-Mancala"]

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"
# Default account for katana with seed = 0
account_address = "0x07C28a0Cb8ef410c5B6fe30397A09636763F67909103b8225c6C04060B4258C5"
private_key = "0x064ddb1260b4a1281c7c03cc2ee4ef5d836ed1f4424ed988dbba9bd7da531d6f"
world_address = "0x07b8e34ccb602915d91d32ede9cc6b51cc253ae5a5066cb0c688219b595a3417"  # Uncomment and update this line with your world address.
ipfs_config.url = "https://ipfs.infura.io:5001"
ipfs_config.username = "2EBrzr7ZASQZKH32sl2xWauXPSA"
ipfs_config.password = "12290b883db9138a8ae3363b6739d220"

[init_call_args]
"mancala_denstwo-Mancala" = [
  "0x0158160018d590d93528995b340260e65aedd76d28a686e9daa5c4e8fad0c5dd",  # TOKEN_PASS_ADDRESS
  "0x07C28a0Cb8ef410c5B6fe30397A09636763F67909103b8225c6C04060B4258C5", # GATEKEEPER_ADDRESS
]
