rpc = "https://api.cartridge.gg/x/starknet/sepolia"

allowed_origins = ["*"]
# The World address to index.
world_address = "0x060809ee8d6337a25650e88f4236e405895b6aa2676439960f4cbfb676b91f54"

# Indexing Options
[indexing]
allowed_origins = ["*"]
pending = true
transactions = true
polling_interval = 1000
contracts = [
    "erc721:0x00c489b121fdc7bf7aa71167d603de7d41184576b6ed1bae87dd7b448c4ac8cf"
]

[events]
raw = true
historical = [
    "mancala_kefir-TrophyProgression",
]
