kind = "DojoContract"
class_hash = "0x73105e8f5b180b9a6d10ff4a1c02e974a237d65e3512cff2f0a3db026c81753"
original_class_hash = "0x73105e8f5b180b9a6d10ff4a1c02e974a237d65e3512cff2f0a3db026c81753"
base_class_hash = "0x0"
abi = "manifests/sepolia/abis/base/contracts/mancala_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "mancala::systems::actions::actions"
