kind = "DojoContract"
class_hash = "0x3d7d97d375882e19ac0b808ef3d7398df8c99f358a947b36ddf577d9e682c5e"
original_class_hash = "0x3d7d97d375882e19ac0b808ef3d7398df8c99f358a947b36ddf577d9e682c5e"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/mancala-actions-5608e015.json"
reads = []
writes = []
init_calldata = []
tag = "mancala-actions"
systems = [
    "initialize_game_counter",
    "join_game",
    "timeout",
    "create_private_game",
    "move",
    "forfeited",
    "request_restart_game",
    "restart_current_game",
]
manifest_name = "mancala-actions-5608e015"
