kind = "DojoContract"
class_hash = "0x1bf064aa3b854cd8adc0c228564241127d0929693c9a96f0eac64959317d4f8"
original_class_hash = "0x1bf064aa3b854cd8adc0c228564241127d0929693c9a96f0eac64959317d4f8"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/mancala_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "mancala::systems::actions::actions"
