kind = "DojoContract"
class_hash = "0x253760f6c7a93d429d0061d0d35383905c84a08bd8d85d1adb3dd557309e990"
original_class_hash = "0x253760f6c7a93d429d0061d0d35383905c84a08bd8d85d1adb3dd557309e990"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/mancala_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "mancala::systems::actions::actions"
