kind = "DojoContract"
class_hash = "0x6e9331b226cf8f6698aebc4b1b9df5113835c5af8ce684bc400cde81106fa7a"
original_class_hash = "0x6e9331b226cf8f6698aebc4b1b9df5113835c5af8ce684bc400cde81106fa7a"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/mancala_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "mancala::systems::actions::actions"
