kind = "DojoContract"
class_hash = "0x38c4404441c9d7ccbb43752cd5ecaa0edb26a7a79507ad294c353cebe0c5faa"
original_class_hash = "0x38c4404441c9d7ccbb43752cd5ecaa0edb26a7a79507ad294c353cebe0c5faa"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/mancala_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "mancala::systems::actions::actions"
