kind = "DojoContract"
class_hash = "0x2e7de5612ed30cf302c854b9d846bc4751885053ecaeb577452b09db852fbe9"
original_class_hash = "0x2e7de5612ed30cf302c854b9d846bc4751885053ecaeb577452b09db852fbe9"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/mancala-actions-5608e015.json"
reads = []
writes = []
init_calldata = []
tag = "mancala-actions"
systems = [
    "initialize_game_counter",
    "join_game",
    "create_private_game",
    "move",
    "forfeited",
    "request_restart_game",
    "restart_current_game",
]
manifest_name = "mancala-actions-5608e015"
