kind = "DojoContract"
class_hash = "0x55dc74c6636df9de2105e32d762287bb5aaf561b491728d07fabc55eb345314"
original_class_hash = "0x55dc74c6636df9de2105e32d762287bb5aaf561b491728d07fabc55eb345314"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/mancala_alpha-actions-2c0baebe.json"
reads = []
writes = []
init_calldata = []
tag = "mancala_alpha-actions"
systems = [
    "create_initial_game_id",
    "join_game",
    "time_out",
    "forfeited",
    "request_restart_game",
]
manifest_name = "mancala_alpha-actions-2c0baebe"
