kind = "DojoContract"
class_hash = "0x17ff2e648f91a97b92a393a452ab4c2d69d482cf186be9f54c7b75b3cd001b2"
original_class_hash = "0x17ff2e648f91a97b92a393a452ab4c2d69d482cf186be9f54c7b75b3cd001b2"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/mancala_alpha-actions-2c0baebe.json"
reads = []
writes = []
init_calldata = []
tag = "mancala_alpha-actions"
manifest_name = "mancala_alpha-actions-2c0baebe"
