kind = "DojoContract"
class_hash = "0x5b0be4aef3910d376c5a14447500df8e32a243546e825840d04a7ab85a9bc20"
original_class_hash = "0x5b0be4aef3910d376c5a14447500df8e32a243546e825840d04a7ab85a9bc20"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/mancala-actions-5608e015.json"
reads = []
writes = []
init_calldata = []
tag = "mancala-actions"
systems = [
    "initialize_game_counter",
    "join_game",
    "timeout",
    "create_private_game",
    "move",
    "forfeited",
    "request_restart_game",
    "restart_current_game",
]
manifest_name = "mancala-actions-5608e015"
